server:
  port: 8760
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/KSWA-SWEEP/Formduo-Config.git
          uri: git@github.com:KSWA-SWEEP/Formduo-Config.git
          ignore-local-ssh-settings: true
          privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            -----END RSA PRIVATE KEY-----
          force-pull: true
    bus:
      enabled: true


  rabbitmq:
    host: rabbitmq
#    rabbitmq
    port: 5672
    username: sweep
    password: sweep

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${DISCOVER_URL:http://service-discovery:8761}/eureka/
#    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: false
      percentiles:
        http:
          server:
            requests: 0.5, 0.9, 0.95, 0.99, 0.999

    tags:
      application: ${spring.application.name} # metric 정보에 대한 라벨링 설정
